require("changes")
require("prototypes.item")
require("prototypes.fluids")
require("prototypes.recipe")
require("prototypes.foods-item-recipe")
require("prototypes.drinks-item-recipe")
require("prototypes.auto-composting-recipe")
require("prototypes.crop")
require("prototypes.entity")
require("prototypes.technology")
require("prototypes.category")
require("prototypes.achievements")
require("prototypes.plants")

require("prototypes.decor.tables-entity")
require("prototypes.decor.tables-recipe")
require("prototypes.decor.tables-item")
require("prototypes.decor.tables-category")

require("prototypes.storages.storage-entity")
require("prototypes.storages.storage-recipe")
require("prototypes.storages.storage-item")

require("prototypes.styles.fi-style-gui")
require("prototypes.styles.fi-font-gui")
require("prototypes.styles.fi-sprites")
require("prototypes.sounds")


require("prototypes.pure-water.fluid")
