data:extend({	
	{
		type = "research-achievement",
		name = "he-need-some-milk",
		order = "w-1",
		technology = "fermentation",
		icon = "__FoodIndustry__/graphics/achievements/he-need-some-milk.png",
		icon_size = 128,
	},
	{
		type = "produce-achievement",
		name = "steamed-hams",
		order = "w-2",
		item_product = "burger",
		amount = 200,
		limited_to_one_game = true,
		icon = "__FoodIndustry__/graphics/achievements/steamed-hams.png",
		icon_size = 128,
	},
	{
		type = "achievement",
		name = "vegan",
		order = "w-4",
		icon = "__FoodIndustry__/graphics/achievements/vegan.png",
		icon_size = 128,
	},
	{
		type = "achievement",
		name = "carnivore",
		order = "w-5",
		icon = "__FoodIndustry__/graphics/achievements/carnivore.png",
		icon_size = 128,
	},
	{
		type = "research-achievement",
		name = "too-lazy-to-eat",
		order = "w-6",
		technology = "food-energy-efficiency-11",
		icon = "__FoodIndustry__/graphics/achievements/too-lazy-to-eat.png",
		icon_size = 128,
	},
	{
		type = "achievement",
		name = "hibernation",
		order = "w-7",
		icon = "__FoodIndustry__/graphics/achievements/hibernation.png",
		icon_size = 128,
	},
	{
		type = "achievement",
		name = "gourmet",
		order = "w-8",
		icon = "__FoodIndustry__/graphics/achievements/gourmet.png",
		icon_size = 128,
	},
	{
		type = "achievement",
		name = "overweight",
		order = "w-9",
		icon = "__FoodIndustry__/graphics/achievements/overweight.png",
		icon_size = 128,
	},
	{
		type = "dont-build-entity-achievement",
		dont_build = { "pumpjack"},
		name = "green-oil",
		order = "w-a",
		icon = "__FoodIndustry__/graphics/achievements/green-oil.png",
		icon_size = 128,
	},
})
