data:extend({
	{
		type = "fluid",
		name = "fertilizer-oil",
		icon = "__FoodIndustry__/graphics/icons/fluids/fertilizer-oil.png",
		icon_size = 32,
		subgroup = "food-fluids",
		base_color = {r = 0.8, g = 0, b = 0.7, a = 1},
		flow_color = {r = 0.7, g = 0.7, b = 0.7, a = 1},
		default_temperature = 15,
		max_temperature = 100,
		heat_capacity = "0.6KJ",
		pressure_to_speed_ratio = 0.15,
		flow_to_energy_ratio = 0.59,
		order = "w-b-j"
	},
	{
		type = "fluid",
		name = "compost-water",
		icon = "__FoodIndustry__/graphics/icons/fluids/compost-water.png",
		icon_size = 32,
		subgroup = "food-fluids",
		base_color = {r = 0.25, g = 0.2, b = 0.5, a = 1},
		flow_color = {r = 0.7, g = 0.7, b = 0.7, a = 1},
		default_temperature = 15,
		max_temperature = 100,
		heat_capacity = "0.2KJ",
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "w-b-h"
	},
	{
		type = "fluid",
		name = "fertilizer-water",
		icon = "__FoodIndustry__/graphics/icons/fluids/fertilizer-water.png",
		icon_size = 32,
		subgroup = "food-fluids",
		base_color = {r = 0.34, g = 0.2, b = 0.6, a = 1},
		flow_color = {r = 0.7, g = 0.7, b = 0.7, a = 1},
		default_temperature = 15,
		max_temperature = 100,
		heat_capacity = "0.2KJ",
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "w-b-i"
	},
	{
		type = "fluid",
		name = "ketchup",
		icon = "__FoodIndustry__/graphics/icons/fluids/ketchup.png",
		icon_size = 32,
		subgroup = "food-intermediates",
		base_color = {r = 0.8, g = 0.1, b = 0.0, a = 1},
		flow_color = {r = 0.7, g = 0.7, b = 0.7, a = 1},
		default_temperature = 15,
		max_temperature = 100,
		heat_capacity = "0.2KJ",
		pressure_to_speed_ratio = 0.3,
		flow_to_energy_ratio = 0.59,
		order = "w-b-i"
	},
	{
		type = "fluid",
		name = "soy-milk",
		icon = "__FoodIndustry__/graphics/icons/fluids/soy-milk.png",
		icon_size = 32,
		subgroup = "food-intermediates",
		base_color = {r = 0.9, g = 0.9, b = 0.8, a = 1},
		flow_color = {r = 0.7, g = 0.7, b = 0.7, a = 1},
		default_temperature = 15,
		max_temperature = 100,
		heat_capacity = "0.2KJ",
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "w-b-i"
	},
	{
		type = "fluid",
		name = "soy-sauce",
		icon = "__FoodIndustry__/graphics/icons/fluids/soy-sauce.png",
		icon_size = 32,
		subgroup = "food-intermediates",
		base_color = {r = 0.3, g = 0.25, b = 0.2, a = 1},
		flow_color = {r = 0.7, g = 0.4, b = 0.1, a = 1},
		default_temperature = 15,
		max_temperature = 100,
		heat_capacity = "0.2KJ",
		pressure_to_speed_ratio = 0.3,
		flow_to_energy_ratio = 0.59,
		order = "w-b-i"
	},
	{
		type = "fluid",
		name = "canola-oil",
		icon = "__FoodIndustry__/graphics/icons/fluids/canola-oil.png",
		icon_size = 32,
		subgroup = "food-intermediates",
		base_color = {r = 0.57, g = 0.45, b = 0.0, a = 1},
		flow_color = {r = 1, g = 0.73, b = 0.1, a = 1},
		default_temperature = 15,
		max_temperature = 100,
		heat_capacity = "0.2KJ",
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
		order = "w-b-i"
	},

	{
		type = "fluid",
		name = "gelatine-broth",
		icon = "__FoodIndustry__/graphics/icons/fluids/gelatine-broth.png",
		icon_size = 32,
		subgroup = "foods-species",
		order = "w-b-4",
		base_color = {r = 0.73, g = 0.61, b = 0.0, a = 1},
		flow_color = {r = 0.788, g = 0.64, b = 0.0, a = 1},
		default_temperature = 45,
		max_temperature = 100,
		heat_capacity = "0.2KJ",
		pressure_to_speed_ratio = 0.4,
		flow_to_energy_ratio = 0.59,
	},
})